compile_mode = "full"
last_build_time = "2026-03-15 15:55:31"
md_dir = "source"
output_dir = "public"

[[sidebar.hot_categories]]
count = 143
name = "posts"

[[sidebar.hot_categories]]
count = 117
name = "blog"

[[sidebar.hot_categories]]
count = 25
name = "docs"

[[sidebar.hot_categories]]
count = 3
name = "projects"

[[sidebar.hot_posts]]
categories = ["blog", "2026"]
date_ymd = "2026-03-04"
slug = "28"
title = "Vide Coding 经验总结，核心五点"

[[sidebar.hot_posts]]
categories = ["blog", "2026"]
date_ymd = "2026-02-28"
slug = "27"
title = "Mise 是一种好软件"

[[sidebar.hot_posts]]
categories = ["projects"]
date_ymd = "2026-02-19"
slug = "enyan"
title = "恩言 - 大字有声圣经"

[[sidebar.hot_posts]]
categories = ["projects"]
date_ymd = "2026-02-19"
slug = "rustpress"
title = "RustPress - 纯静态博客引擎"

[[sidebar.hot_posts]]
categories = ["blog", "2026"]
date_ymd = "2026-02-19"
slug = "26"
title = "我用 AI 写了四五个软件之后的总结"

[[sidebar.hot_posts]]
categories = ["blog", "2026"]
date_ymd = "2026-02-19"
slug = "25"
title = "恩言-大字有声圣经发布了"

[[sidebar.hot_posts]]
categories = ["blog", "2026"]
date_ymd = "2026-02-18"
slug = "23"
title = "板栗是人是狗？"

[[sidebar.hot_posts]]
categories = ["blog", "2026"]
date_ymd = "2026-02-15"
slug = "22"
title = "写福字"

[[sidebar.hot_posts]]
categories = ["blog", "2026"]
date_ymd = "2026-02-14"
slug = "21"
title = "那个把代码当拖拉机修的小镇青年，活成了王阳明眼中最好的状态"

[[sidebar.hot_posts]]
categories = ["blog", "2026"]
date_ymd = "2026-02-07"
slug = "18"
title = "有一个家伙说 Vide Coding 上瘾"

[[sidebar.hot_tags]]
count = 1
name = "7x24 AI 员工"

[[sidebar.hot_tags]]
count = 15
name = "AI"

[[sidebar.hot_tags]]
count = 3
name = "AI IDE"

[[sidebar.hot_tags]]
count = 1
name = "AI IDE生产力"

[[sidebar.hot_tags]]
count = 1
name = "AI 办公效率提升"

[[sidebar.hot_tags]]
count = 1
name = "AI 文件管理安全"

[[sidebar.hot_tags]]
count = 1
name = "AI 架构能力"

[[sidebar.hot_tags]]
count = 1
name = "AI 编程技巧"

[[sidebar.hot_tags]]
count = 1
name = "AI 自动化服务器"

[[sidebar.hot_tags]]
count = 1
name = "AI代码生成"

[[sidebar.hot_tags]]
count = 1
name = "AI助手"

[[sidebar.hot_tags]]
count = 1
name = "AI助手自动化"

[[sidebar.hot_tags]]
count = 1
name = "AI学习"

[[sidebar.hot_tags]]
count = 1
name = "AI总结"

[[sidebar.hot_tags]]
count = 1
name = "AI时代"

[[sidebar.hot_tags]]
count = 1
name = "AI时代行动力"

[[sidebar.hot_tags]]
count = 1
name = "AI笔记软件"

[[sidebar.hot_tags]]
count = 4
name = "AI编程"

[[sidebar.hot_tags]]
count = 1
name = "AI编程上瘾"

[[sidebar.hot_tags]]
count = 1
name = "AI编程工具"
